### ISSUE TITLE
transfer to org

### ISSUE THREAD

**Issue by DanielRuf** [mikolajdobrucki/material-foundation#46]
The project should be under an org and the fork of @d0whc3r should be merged and the release for npmjs should come from this new repo.

**Comment by eucalyptuss** [comment]
release for npmjs in now under npmjs.com/materialfoundation

**Comment by DanielRuf** [comment]
Not sure if this was the answer to my questions.

It's still under your name / not transferred to an org or did I miss this?

Not sure if the fork is merged, will check this in the next days.

The release on npmjs should be from an org, not your GH account (better rights management, easier collaboration, less risks, more open for maintainers, lower truck factor, ...).

**Comment by mikolajdobrucki** [comment]
you're absolutely right, sorry for the confusion

**Comment by DanielRuf** [comment]
Bump.
